[package]
name = "sss_code"
version = "0.1.4"
edition = "2021"
publish = false
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "sss_code"
path = "./src/main.rs"

[dependencies]
clap.workspace = true
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
clap-stdin = "0.4.0"
sss_lib = { path = "../sss_lib" }
syntect = { version = "5.1.0", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "regex-onig",
    "dump-load",
    "plist-load",
    "yaml-load",
] }
