[package]
name = "sss_code"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
thiserror.workspace = true
clap-stdin = "0.3.0"
sss_lib = { path = "../sss_lib" }
syntect = { version = "5.1.0", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "regex-onig",
    "dump-load",
    "plist-load",
    "yaml-load"
] }
