[package]
name = "sss_code"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "sss_code"
path = "./src/main.rs"

[dependencies]
clap.workspace = true
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
clap-stdin = "0.3.0"
conv = "0.3.3"
font-kit = "0.11.0"
pathfinder_geometry = "0.5.1"
sss_lib = { path = "../sss_lib" }
syntect = { version = "5.1.0", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "regex-onig",
    "dump-load",
    "plist-load",
    "yaml-load"
] }
