[package]
name = "code_screenshot"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
opt-level = 3
codegen-units = 1

[target.'cfg(not(target_family="wasm"))'.profile.dev.package."*"]
opt-level = 3

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
syntect = { version = "5.1.0", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "regex-fancy",
] }
clap = { version = "4.4.8", features = ["derive", "color", "env", "suggestions", "wrap_help"] }
