allow-branch = ["main", "dev", "!HEAD"]
publish = false
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-prefix = "{{crate_name}}/"
tag-name = "{{prefix}}v{{version}}"
