[package]
name = "sss_cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "sss"
path = "./src/main.rs"

[dependencies]
clap.workspace = true
screenshots = "0.8.6"
sss_lib = { path = "../sss_lib" }
arboard = { version = "3.3.0", features = ["wayland-data-control"] }
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client"] }
