[package]
name = "sss_cli"
description = "Take pretty screenshot to your screen"
version = "0.1.2"
publish = false
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sss"
path = "./src/main.rs"

[package.metadata.dist]
dist = true

[package.metadata.wix]
upgrade-guid = "CF05D879-DF84-4B30-BAEF-1B68E1DAD701"
path-guid = "50D7445F-C399-4C23-A8FF-6BE599929DE9"
license = false
eula = false

[dependencies]
clap.workspace = true
toml.workspace = true
serde.workspace = true
merge2.workspace = true
directories.workspace = true
mouse_position = "0.1.3"
screenshots = "0.8.6"
sss_lib = { path = "../sss_lib" }

[target.x86_64-unknown-linux-gnu.dependencies]
libwayshot = "0.3.0"
