[package]
name = "sss_cli"
version = "0.1.0"
publish = false
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sss"
path = "./src/main.rs"

[dependencies]
clap.workspace = true
libwayshot = "0.3.0"
screenshots = "0.8.6"
sss_lib = { path = "../sss_lib" }
