[package]
name = "sss_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sss"
path = "./src/main.rs"

[dependencies]
screenshots = "0.8.6"
sss_lib = { path = "../sss_lib" }
clap = { version = "4.4.8", features = [
    "derive",
    "color",
    "env",
    "suggestions",
    "wrap_help",
] }
