[package]
name = "sss_select"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
raqote = "0.8.3"
winit = "0.29.8"
softbuffer = { version = "0.4.0", default-features = false, features = ["x11", "wayland"] }
